name = "***"
compatibility_date = "***"

[env.dev.vars]
ENVIRONMENT="dev"
BASE_URL="http://localhost:8787"
CLIENT_URL="http://localhost:5173"
GOOGLE_CLIENT_ID=""
GOOGLE_CLIENT_SECRET=""

[env.test]
# テスト専用のDB
d1_databases = [
  { binding = "DB", database_name = "test_evodo_openapi", database_id = "test", migrations_dir = "./drizzle" }
]
kv_namespaces = [
  { binding = "KV", id = "test" }
]

[env.dev]
# ローカルで動かすときのDB
d1_databases = [
  { binding = "DB", database_name = "evodo_openapi", database_id = "***", migrations_dir = "./drizzle" }
]
kv_namespaces = [
  { binding = "KV", id = "***" }
]