/**
 * Generated by orval v6.22.1 🍺
 * Do not edit manually.
 * My API
 * OpenAPI spec version: 1.0.0
 */
export type PostUsersBody = {
  name: string;
};

export interface User {
  createdAt: string;
  id: string;
  name: string;
  updatedAt: string;
}
