name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Test and deploy to workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          secrets: |
            GOOGLE_CLIENT_ID
            GOOGLE_CLIENT_SECRET
          vars: |
            ENVIRONMENT
            CLIENT_URL
            BASE_URL
          # https://github.com/cloudflare/wrangler-action/issues/209#issuecomment-1868189425
          wranglerVersion: 3.15.0
          environment: prod
          packageManager: pnpm
          workingDirectory: backend
          preCommands: |
            pnpm test-setup
            pnpm test
            pnpm db:migrations
          command: deploy --minify src/index.ts
        env:
          ENVIRONMENT: ${{ vars.ENVIRONMENT }}
          CLIENT_URL: ${{vars.CLIENT_URL}}
          BASE_URL: ${{vars.BASE_URL}}
          GOOGLE_CLIENT_ID: ${{secrets.GOOGLE_CLIENT_ID}}
          GOOGLE_CLIENT_SECRET: ${{secrets.GOOGLE_CLIENT_SECRET}}

      - name: Test and deploy to pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          # https://github.com/cloudflare/wrangler-action/issues/209#issuecomment-1868189425
          wranglerVersion: 3.15.0
          packageManager: pnpm
          workingDirectory: frontend
          preCommands: |
            pnpm test
            pnpm build
          command: pages deploy dist --project-name evodo-openapi
        env:
          VITE_API_URL: ${{vars.BASE_URL}}
